import os
from typing import TypedDict
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from dotenv import load_dotenv
from google import genai
from langgraph.graph import StateGraph, START, END

# Load environment variables from .env file
load_dotenv()

app = FastAPI(title="if/else Atlas Agent Backend (Gemini)")

# Enable CORS for frontend requests
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Allows all origins for local development simplicity
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Pydantic schemas for request and response
class ChatRequest(BaseModel):
    message: str

class ChatResponse(BaseModel):
    response: str

# Define LangGraph state schema
class AgentState(TypedDict):
    message: str
    response: str

# Define the LangGraph node
def send_to_gemini_node(state: AgentState) -> dict:
    api_key = os.getenv("GEMINI_API_KEY", "").strip()
    model = os.getenv("GEMINI_MODEL", "gemini-2.5-flash")
    
    if not api_key or api_key.startswith("your-api-key"):
        # Graceful fallback to help testing without credentials initially
        return {
            "response": (
                "Hello! The backend and LangGraph orchestration are working successfully. "
                "However, GEMINI_API_KEY is not set in backend/.env. "
                "Please configure a valid key from Google AI Studio to talk to Gemini."
            )
        }
    
    try:
        # Initialize official Google GenAI client
        client = genai.Client(api_key=api_key)
        try:
            response = client.models.generate_content(
                model=model,
                contents=state["message"],
            )
            return {"response": response.text or "No response generated by Gemini."}
        except Exception as api_err:
            err_str = str(api_err)
            # If the model is experiencing high demand (503), attempt a fallback model
            if "503" in err_str or "UNAVAILABLE" in err_str or "demand" in err_str:
                fallback_model = "gemini-1.5-flash" if model != "gemini-1.5-flash" else "gemini-1.5-pro"
                print(f"Primary model {model} unavailable. Retrying with fallback: {fallback_model}...")
                fallback_response = client.models.generate_content(
                    model=fallback_model,
                    contents=state["message"],
                )
                return {
                    "response": (
                        f"[Fallback Mode: {fallback_model}] \n\n"
                        f"{fallback_response.text or 'No response generated by Gemini fallback.'}"
                    )
                }
            else:
                raise api_err
    except Exception as e:
        return {"response": f"Failed to call Gemini API: {str(e)}"}

# Build LangGraph workflow
workflow = StateGraph(AgentState)
workflow.add_node("agent", send_to_gemini_node)
workflow.add_edge(START, "agent")
workflow.add_edge("agent", END)

# Compile LangGraph app
compiled_graph = workflow.compile()

@app.post("/chat", response_model=ChatResponse)
async def chat(payload: ChatRequest):
    try:
        # Run the minimal graph and pass the message
        initial_state = {"message": payload.message, "response": ""}
        result = compiled_graph.invoke(initial_state)
        return ChatResponse(response=result.get("response", "No response generated."))
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Internal Server Error: {str(e)}")

if __name__ == "__main__":
    import uvicorn
    # Use config from env, default to port 8000
    port = int(os.getenv("PORT", 8000))
    host = os.getenv("HOST", "0.0.0.0")
    uvicorn.run("main:app", host=host, port=port, reload=True)
